version: "3"
services:
  pg:
    image: postgres:11
    container_name: barrigaDB
    restart: always
    environment:
     - POSTGRES_DB=barrigaDB
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=332329
    ports:
     - 5432:5432
